### PR TITLE
Fix for parsing "null" values for auto-value objects.

### PR DESCRIPTION
**Pull request by radzio**

### CODE REVIEW

**Comment by rharter** [comment]
Thanks for the PR. It looks like this caused the tests to fail, and also needs tests for your addition.

**Comment by radzio** [comment]
@rharter  no problem. I didn't updated tests for this. But I've tested it manually and it's working like a charm :-)

**Comment by rharter** [comment]
@radzio Are you planning to add tests for your changes?  I won't be merging in untested code.

**Comment by R4md4c** [comment]
Hello @radzio,

Are you planning to add tests for this fix? I'm interested in merging this PR. If you don't have time I can step in to write the tests.

**Comment by rharter** [comment]
@R4md4c Are you still up for writing tests for this and rebasing it?

**Comment by R4md4c** [comment]
@rharter Yes, I'm still up for it, but I'm wondering whether I should open a new pull request or I use the current pull request?

**Comment by rharter** [comment]
You can always check out his branch into your own fork and make a new PR.

**Comment by muddin1** [comment]
@rharter  I use `nullSafe()` in my custom `AutoValueTypeAdapterFactory` but now that `AutoValueGsonTypeAdapterFactory` is introduced in 0.3.0, I can't really use the generated implementation because it doesn't include `nullSafe()`. Is this pull request going to fix that?

**Comment by R4md4c** [comment]
I tried to write test for this PR, but I realized that it doesn't solve anything  when trying to read a null auto value object from the JSON string as it reads it without a problem. 

Perhaps I misunderstood what problem this PR solves?

Here is the test method 
```
@Test
    public void testReadingNullAutoValueObject() throws Exception {
        Gson gson = new GsonBuilder()
                .registerTypeAdapterFactory(new PersonTypeAdapterFactory())
                .create();
        Person person = Person.builder()
                .name("Piasy")
                .gender(1)
                .age(23)
                .build();
        String fromJson = "{\"name\":\"Piasy\",\"gender\":1,\"age\":23,\"facility\":null}";
        Person fromJsonPerson = gson.fromJson(fromJson, Person.class);

        Assert.assertEquals(person, fromJsonPerson);
    }
```

Here is what I added in the Person class.

**Comment by R4md4c** [comment]
I tried to write test for this PR before applying the patch to check what problem it does solve, but I realized that it doesn't solve anything  when trying to read a null auto value object from the JSON string as it reads it without a problem. 

Perhaps I misunderstood what problem this PR solves?

Here is the test method 
```
   @Test
    public void testReadingNullAutoValueObject() throws Exception {
        Gson gson = new GsonBuilder()
                .registerTypeAdapterFactory(new PersonTypeAdapterFactory())
                .create();
        Person person = Person.builder()
                .name("Piasy")
                .gender(1)
                .age(23)
                .build();
        // Notice the null facility. 
        String fromJson = "{\"name\":\"Piasy\",\"gender\":1,\"age\":23,\"facility\":null}";
        Person fromJsonPerson = gson.fromJson(fromJson, Person.class);

        Assert.assertEquals(person, fromJsonPerson);
    }
```

Here is what I added to the ```Person``` class.
```
   @Nullable
    public abstract Facility facility(); // An AutoValue object that contains an integer.
```

**Pull request closed without merging**
