### PR TITLE
Refactor code that was using Java 8 features

### PR DESCRIPTION
**Pull request by jakekdodd**
Broken in #157 

(sorry for the couple of automatic whitespace changes...I can resubmit without those if you wish)

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why? AutoValue's processor requires Java 8 so this isn't going to prevent the requirement to use JDK 8 in your builds.

**Comment by jakekdodd** [comment]
@JakeWharton #157. I didn't read through the [whole conversation](https://github.com/rharter/auto-value-gson/issues/142#issuecomment-349002607) but you're welcome to do so.

The build on `master` is [failing](https://travis-ci.org/rharter/auto-value-gson/builds/356921700) (regardless of whether you build with JDK 7 or 8—I haven't touched 7 in years) and the fix only took a minute, so I did it. Since AutoValue's processor requires JDK 8 anyways, we should probably just revert the commit(s) that busted the build

**Comment by NightlyNexus** [comment]
isn't this change the culprit?
https://github.com/rharter/auto-value-gson/pull/145
why did the build for it succeed?

**Comment by jakekdodd** [comment]
@NightlyNexus the CI build happened last August when that PR was first submitted, which was before the Java 8 source was merged

**Comment by NightlyNexus** [comment]
ahaha. good eye. perhaps Ryan would accept a PR to revert that.

**Pull request closed without merging**
